linters:
  # Enable all available linters.
  # Default: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  wsl:
    strict-append: false
    enforce-err-cuddling: true

issues:
  exclude-rules:
    - path: pkg/hash/hash.go
      text: "SA1019"