name: pwdsafety
summary: CLI tool checking password safety
description: |
      Takes as input a password and output a score of strengthness. If not sufficiently strong, it suggests a random password.
version: v0.4.0
grade: stable
base: core20

confinement: strict

apps:
  pwdsafety:
    command: bin/pwdsafety

parts:
  pwdsafety:
    plugin: go
    source-type: git
    source: https://github.com/edoardottt/pwdsafety